WIP: switch to Tox + pyup.io
mozilla/mozwebqa-examples pull request #9
Opened 2016-12-29 23:13 UTC by stephendonner

Caveats:
1) Very much a work in progress.
2) Doesn't run; error output here: https://pastebin.mozilla.org/8957146
3) I'm doing a bunch of these Tox/pyup.io PRs today, so apologies in advance; I'm very likely to have missed something

Starts to address the following:

* Switch to Tox: https://github.com/mozilla/mozwebqa-examples/issues/7
* Enable pyup.io: https://github.com/mozilla/mozwebqa-examples/issues/8
* Fix/populate empty README: https://github.com/mozilla/mozwebqa-examples/issues/2

@davehunt feedback/r? highly welcome!

2017-01-05 11:49 UTC, davehunt requested changes

2017-01-05 11:49 UTC, davehunt commented on .travis.yml
> +  - TOXENV=flake8
This will cause only the `flake8` environment to run in Travis CI.

2017-01-05 11:49 UTC, davehunt commented on requirements/tests.txt
> +Flask
Flask is a requirement for the application under test. All other requirements are for the tests themselves. I would create a `base.txt` for the application requirements, and make `tests.txt` include these.

2017-01-05 11:49 UTC, davehunt commented on setup.cfg
> +python_files=test_*.py
I believe this is the default, so shouldn't be needed.

2017-01-05 11:49 UTC, davehunt commented on setup.cfg
> +addopts=-n=auto --verbose -r=a --junit-xml=results/junit.xml
We're not currently running these tests in parallel in Travis CI, so I wonder if we should avoid introducing this (we should probably remove the pytest-xdist dependency too, if there's an issue with running them in parallel).

2017-01-05 11:49 UTC, davehunt commented on tox.ini
> +envlist = tests, flake8
I think we should run these tests in multiple Python versions, but that can be a later enhancement.

2017-01-05 11:49 UTC, davehunt commented on tox.ini
> +commands = py.test {posargs}
Nit: Remove the dot from `py.test`

2017-01-05 11:49 UTC, davehunt commented on .travis.yml
> -script: "py.test -v --driver Firefox --variables variables.json tests"
We still need to pass the variables file, though we can probably just do this in `tox.ini` as this file is in tree and contains no real secrets.

2017-01-21 09:02 UTC, stephendonner commented on .travis.yml
> -script: "py.test -v --driver Firefox --variables variables.json tests"
I gave this a stab - I /think/ it's actually being passed in, but as there are new (hopefully unrelated and are rather from this repo last being touched 8 months ago).

2017-01-21 09:03 UTC, stephendonner commented on tox.ini
> +envlist = tests, flake8
+1 - I volunteer to help with a sweep of our projects, at some point in the future, given priorities + time :-)

2017-01-21 09:04 UTC, stephendonner commented
@davehunt feedback/r?  - definitely need help understanding and trying to address the actual test failures, now, which we'll need, probably, for this PR to be merged.  Thanks as always!

2017-01-23 11:40 UTC, davehunt requested changes
This is failing for Python 2.7 because it's depending on a private method from pytest-selenium that was moved to pytest-base-url. You could resolve this by pinning to pytest-selenium 1.2.1, or by changing lines 36-37 of `conftest.py` to:

```python
from pytest_base_url import plugin
plugin._verify_url(request, base_url)
```

I think we can safely drop support for Python 2.6, so let's do that and ignore those failures.

2017-01-23 11:40 UTC, davehunt commented on setup.cfg
> +addopts = --variables=variables.json --verbose -r=a --junit-xml=results/junit.xml
This approach should work, but I'd at least put `--variables` and `--junit-xml` directly into `tox.ini` in the `commands` line. You're also missing the `--driver` default value.

2017-01-23 11:42 UTC, davehunt requested changes
Thinking about this some more, I am not sure it's worth the effort getting this repository into a good state. I think it would be more useful to point contributors to https://github.com/davehunt/cookiecutter-pytest-selenium, which creates a local project with tests that use our recommended practices and tools. What do you think @stephendonner?

2017-01-23 23:40 UTC, stephendonner commented
@davehunt yes, I'd be fine (happy, even) with just focusing our efforts on pointing people to (and helping file/fix Issues) cookiecutter-pytest-selenium.  Should we now work on decommissioning this repo with a notice, etc.?  And, if so, just leave as-is, (code-wise), but change the readme?

2017-01-24 08:26 UTC, davehunt commented
I doubt anyone is using this repository, but let's do what we did with moz-grid-config and note in the README that we're no longer using or maintaining it. https://github.com/mozilla/moz-grid-config

2017-02-09 11:39 UTC, stephendonner commented
imma close this and since we decided to just update the README with a notice, next up is a PR for that, separately.

2017-02-09 11:39 UTC, closed without merging